### ISSUE TITLE
Link to edit album displayed to all users (even if they has not rights)

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeGallery#46]
Enable collaborative albums -> Disabled

Elgg 1.9.8 - hypeGallery 3.1.0-dev

![image](https://cloud.githubusercontent.com/assets/6679837/6370855/54d19538-bcf5-11e4-9a4d-b77b44e183e1.png)

**Comment by hypeJunction** [comment]
Can't reproduce.
