### ISSUE TITLE
Fatal error editing an album

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeGallery#52]
If you add an image from the album editing form, this error falls into a blank page.

2015/04/21 09:59:14 [error] 3440#0: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use object of type ElggBatch as array in hypeGallery/actions/upload/handle.php on line 79" while reading response header from upstream

**Comment by hypeJunction** [comment]
Can't confirm.
