### ISSUE TITLE
Icons are not generated in Elgg 1.10

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeGallery#53]
Tested with hypeFilestore 3.1.0 and all 3rd party plugins disabled.

2015/04/21 10:54:19 [error] 1058#0: *7496 FastCGI sent in stderr: "PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "finfo_file(icons/9558small.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "mime_content_type(icons/9558small.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "finfo_file(icons/9558medium.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "mime_content_type(icons/9558medium.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "finfo_file(icons/9558large.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "mime_content_type(icons/9558large.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "finfo_file(icons/9558800x200.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-04-21 03:54:18 (PDT): "mime_content_type(icons/9558800x200.png): failed to open stream: No such file or directory" in file  /htdocs/engine/classes/ElggFile.php (line 154)

...and I think it generates this Fatal error:

Fatal Error.

Serialization of 'SimpleXMLElement' is not allowed

Exception Object
(
[message:protected] => Serialization of 'SimpleXMLElement' is not allowed
[string:Exception:private] => exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in /home/www/redup_triploader_com/htdocs/mod/hypeGallery/actions/upload/handle.php:113
Stack trace:
#0 /home/www/redup_triploader_com/htdocs/mod/hypeGallery/actions/upload/handle.php(113): serialize(Object(ElggBatch))
#1 /home/www/redup_triploader_com/htdocs/mod/hypeGallery/actions/edit/object/hjalbum.php(71): include('/home/www/redup...')
#2 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/ActionsService.php(70): include('/home/www/redup...')
#3 /home/www/redup_triploader_com/htdocs/engine/lib/actions.php(20): Elgg\ActionsService->execute('edit/object/hja...')
#4 [internal function]: _elgg_action_handler(Array, 'action')
#5 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Router.php(80): call_user_func('_elgg_action_ha...', Array, 'action')
#6 /home/www/redup_triploader_com/htdocs/index.php(60): Elgg\Router->route(Object(Elgg\Http\Request))
#7 {main}
[code:protected] => 0
[file:protected] => /home/www/redup_triploader_com/htdocs/mod/hypeGallery/actions/upload/handle.php
[line:protected] => 113
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /home/www/redup_triploader_com/htdocs/mod/hypeGallery/actions/upload/handle.php
[line] => 113
[function] => serialize
[args] => Array
(
[0] => ElggBatch Object
(
[results:ElggBatch:private] => Array
(
[0] => hypeJunction\Gallery\hjAlbumImage Object
(
[filestore:ElggFile:private] => ElggDiskFilestore Object
(
[dir_root:ElggDiskFilestore:private] => /home/www/redup_triploader_com/data/
[CONFIG:ElggDiskFilestore:private] => stdClass Object
(

**Comment by insideth** [comment]
@Ismayil, doing more tests I realized the icons are generated but with a wrong size, for example the 800x200px one is generated with 267x200px.

Any suggestion to solve it?

Log:

2015/07/02 13:51:56 [error] 1187#0: *6608 FastCGI sent in stderr: "PHP message: PHP WARNING: 2015-07-02 13:51:52 (CEST): "finfo_file(icons/9797small.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-07-02 13:51:52 (CEST): "mime_content_type(icons/9797small.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-07-02 13:51:52 (CEST): "finfo_file(icons/9797medium.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-07-02 13:51:52 (CEST): "mime_content_type(icons/9797medium.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-07-02 13:51:53 (CEST): "finfo_file(icons/9797large.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-07-02 13:51:53 (CEST): "mime_content_type(icons/9797large.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-07-02 13:51:53 (CEST): "finfo_file(icons/9797800x200.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 148)
PHP message: PHP WARNING: 2015-07-02 13:51:53 (CEST): "mime_content_type(icons/9797800x200.jpg): failed to open stream: No such file or directory" in file /home/www/redup_triploader_com/htdocs/engine/classes/ElggFile.php (line 154)
PHP message: PHP WARNING: 2015-07-02 13:51:54 (CEST): "finfo_file(icons/97970.jpg): failed to open stream: No such file or directory" in file /home/www/redup_trip

**Comment by hypeJunction** [comment]
Should be fixed.
